CFLAGS = -std=gnu11 -g
EXES   = q1 q2 bubble_sort_dynamic bubble_sort_awesome
OBJS   = q1.o q2.o bubble_sort_dynamic.o bubble_sort_awesome.o

all:  $(EXES)
clean:
	rm -f $(OBJS) $(EXES)
tidy:
	rm -f $(OBJS)


q1: q1.o
q2: q2.o
bubble_sort_dynamic: bubble_sort_dynamic.o
bubble_sort_awesome: bubble_sort_awesome.o
